### ISSUE TITLE
If more than 1 project is open, only the first one is compiled

### ISSUE THREAD

**Issue by MadBit010** [gosukiwi/atom-agk#1]
As written in the title. I can only select a project to compile if I move it up as the first project.
Would be nice if we could choose a project.

**Comment by gosukiwi** [comment]
Mmm, I wonder if this is the behaviour you want though. Say you have two open projects, A and B. You edit a file in project A, press F5, it compiles and runs project A. You edit a file in project B, press F5, you compile and run project B.

I think this is intuitive. If you see a select project dialog instead, most of the time you will want to just compile the project you are looking at, and the dialog can get annoying.

Any use case in particular you find this could be useful?

**Comment by MadBit010** [comment]
If it was as you describe it, that would be great, too. For me, no matter what file I'm working on, only the first project is compiled. Could it be that it's a setting in Atom?

A dialog box at every compile process would actually be too annoying. I would have rather thought about how in the classic editor to select a project that stays active all the time. could be set as a dropdownbox next to the compile button.

And thanks for the quick response.

**Comment by gosukiwi** [comment]
Ah I see what you mean. I normally just use one instance of Atom per folder, never tried using `File -> Add Project Folder`.

I'll see what I can do :)

**Comment by gosukiwi** [comment]
Thanks @MadBit010 ! v0.3.1 is up and it addresses this issue by properly guessing which project you want to compile based on the file you are currently looking at.

**Comment by MadBit010** [comment]
Ahhh, now it works. Thank you.
