### ISSUE TITLE
Overwriting text does not work.

### ISSUE THREAD

**Issue by MadBit010** [gosukiwi/atom-agk#11]
First of all, thanks for the fast completion of the _issues_.

I don't know if it's _Atom_ or your _plugin_. But with the **Ins** key you can switch between _insert_ and _overwrite_. That strangely enough doesn't work.

Can you help?

**Comment by gosukiwi** [comment]
Uhm this is weird. When I press `Ins` it doesn't work, not even in Notepad or Chrome. There might be something wrong with my computer. Could you try disabling the `atom-agk` plugin temporarily and see if it's still not working?

**Comment by MadBit010** [comment]
It seems to be Atom. I uninstalled your plugin and it still didn't work. After a little googling, I came across [this](https://discuss.atom.io/t/insert-key-doesnt-work/73753). There is a plugin mentioned which I use now and it works.
It's really sad that atom doesn't have that as a core function.

**Comment by gosukiwi** [comment]
Indeed. Weird for Atom not to implement it. 

To be fair you are the first person I meet who uses that key :) Have you tried out [vim-mode-plus](https://atom.io/packages/vim-mode-plus)? If you are into keyboard editing you will love Vim. It does have quite a steep learning curve though.
