### ISSUE TITLE
Highlighting the error messages in the terminal

### ISSUE THREAD

**Issue by MadBit010** [gosukiwi/atom-agk#16]
It is more a request / suggestion.

- Highlighting error messages in the terminal
- Quick navigation to the error by clicking.
- Highlight error lines in the editor.

**Comment by gosukiwi** [comment]
Great suggestion! Addressed in `0.6.0`

![demo](https://user-images.githubusercontent.com/161972/86060337-e751f900-ba3a-11ea-9d87-5e2016d7874f.gif)
