### ISSUE TITLE
Limit of Codecompletion?

### ISSUE THREAD

**Issue by MadBit010** [gosukiwi/atom-agk#19]
Is there a limit to filtering code completion somewhere?
Not all contents are suggested.
I have a large number of constants and UDTs that start with 'nk_'. The first 100 or so (I haven't counted them yet) are suggested.

For example:
In my code I have defined the constant NK_TREE_NODE. If I now enter 'NK_TR', it only suggests NK_TRUE (which is also defined!).
All other constants UDTs that come after NK_TREE_NODE are not listed. Only those that were defined before. Functions are not affected.

![Sample](https://i.imgur.com/wWD99pK.gif)

**Comment by gosukiwi** [comment]
Yes, the autocompletion feature core is in the `autocomplete-plus` package. So just press `ctrl-,` go to `Packages`, type `autocomplete-plus`, then click `Settings`.

There there is an option `Maximum Visible Suggestions` which defaults to 10. There are also some other settings to play around with :) 

Note that at the moment, I'm not using the `Minimum Word Length`, in this plugin, it always defaults to 3 and cannot be changed. I could use that setting instead.

**Comment by MadBit010** [comment]
Ok here is one of my Projects.

[Nuklear-Projects.zip](https://github.com/gosukiwi/atom-agk/files/4846715/Nuklear-Projects.zip)

**Comment by gosukiwi** [comment]
Fixed in `0.5.3`, thanks for providing the demo @MadBit010 !
