### ISSUE TITLE
function inside the current file

### ISSUE THREAD

**Issue by santiworld** [gosukiwi/atom-agk#20]
Hi, it would be good to have a quick access list of all funcions in the file you are working. Same with Types.

**Comment by gosukiwi** [comment]
Good idea. Thanks @santiworld.

Note that I edited your post a bit, hope you don't mind. This way I can use this as a reference and it's easy for me to understand later on.

**Comment by gosukiwi** [comment]
Implemented in `0.8.0` :)

**Comment by santiworld** [comment]
you!!! youuuu!! excelent !!!!! thanksssss!!!
