### ISSUE TITLE
remark the files .agc than other files in the left

### ISSUE THREAD

**Issue by santiworld** [gosukiwi/atom-agk#21]
![image](https://user-images.githubusercontent.com/52417237/86066179-de1b5900-ba47-11ea-9c08-fd18699389da.png)

maibe is good to remark the .agc files in the left, because, the .exe and other file don't have much importance like the .agc files.

**Comment by gosukiwi** [comment]
Hi @santiworld :) Thanks for the issue.

This can be done with version control. Having a configured git repository will make this work out of the box. So it's not the job of this plugin.
