### ISSUE TITLE
another tip or advice

### ISSUE THREAD

**Issue by santiworld** [gosukiwi/atom-agk#23]
hi, i don't know if its possible, or how difficult is this, but, i think maibe is good to have some to show functions, if, for, lined to the left.

sorry my english. :)

![image](https://user-images.githubusercontent.com/52417237/86156709-c2ae5d80-badc-11ea-8e02-cd7dc6107fed.png)

**Comment by gosukiwi** [comment]
Hi @santiworld , I'm closing this, as we talked on Discord, this can be done with `Show Indent Guides`.
