### ISSUE TITLE
compiler ok, no problem icon! green light!

### ISSUE THREAD

**Issue by santiworld** [gosukiwi/atom-agk#24]
Hi, when you make compiler or check for error, maibe is good to have some green light icon, that everything is good, or ok.

in my Terminal is all dark, so i need to see very close to know what terminal says.

![image](https://user-images.githubusercontent.com/52417237/86161881-52a3d580-bae4-11ea-87fd-fc96a70b585c.png)

the green icon below is added by photoshop to show an example

**Comment by gosukiwi** [comment]
Addressed in `0.7.0` :)
