### ISSUE TITLE
info about that Function!

### ISSUE THREAD

**Issue by santiworld** [gosukiwi/atom-agk#25]
hi, working with AGK-ATOM i noted that it will be good to have information about the fields of the functions im editing.

some functions, you don't remember what data go in what place, so, i go to show in a image from IDeal with blitz3D.

sorry my english!!

regards!!!!!

![temp](https://user-images.githubusercontent.com/52417237/86806417-37d6e100-c04f-11ea-81d7-0daa8a86e9cf.JPG)

**Comment by gosukiwi** [comment]
While this is a nice feature, I think the autocomplete + go to definition should be enough to know the arguments needed for a function.

Also, now that there is a symbol explorer, it tells you which arguments are expected for each function. So I think this is a bit redundant.

**Comment by santiworld** [comment]
hi, yes but, autocomplete works if you creating, but if you go to edit,
there is no info about the function.

regards!

**Comment by gosukiwi** [comment]
Mmm true, but at least the Symbol Explorer shows info on all functions in the current file, you can look it up there. While it's not as convenient, I'd really like to avoid changing the status line.
