### ISSUE TITLE
 Code completion no longer works!

### ISSUE THREAD

**Issue by MadBit010** [gosukiwi/atom-agk#27]
since update 0.8.0, code completion does not work anymore. The new symbol explorer doesn't show me anything either. 
Do I have to change some settings? or what is the reason for that?

**Comment by gosukiwi** [comment]
Mmm that's weird. Do you get any kind of error? Do you see any error if you do `ctrl-shift-i`? Also, does this happen for all codebases or just a particular project?

**Comment by MadBit010** [comment]
this is what ctrl+shift+i displays

console output:
![grafik](https://user-images.githubusercontent.com/37149309/87349617-dfc04300-c556-11ea-989a-3e313d6316ec.png)

i dont know what it means.

and this is for all projects.

**Comment by gosukiwi** [comment]
Uhm, interesting. The output is normal, so no javascript errors there. Maybe try disabling/enabling the package again?

What if you try opening the following skeleton project: [example.zip](https://github.com/gosukiwi/atom-agk/files/4915079/example.zip)

Just don't open it as project, go to `File -> Open Folder` and select the extracted `example` folder. Does it still not work?

**Comment by MadBit010** [comment]
Unfortunately, none of this has helped either.

But maybe this will help.
![Sample](https://i.imgur.com/yIKwCPM.gif)

by the way, it would also be good to see constants in the symbol explorer.

**Comment by gosukiwi** [comment]
Nice! Being able to reproduce helps a lot. I pushed a new patch, `v0.8.2` which addresses that particular issue. Hopefully it makes it work for you now ^^;

**Comment by MadBit010** [comment]
At first sight it looks good. All types and functions seem to be there.

Thanks.
