### ISSUE TITLE
Do not open terminal on initial load

### ISSUE THREAD

**Issue by gosukiwi** [gosukiwi/atom-agk#5]
When you first open an AGK project, the terminal opens. It's good to know it exists, I guess, but it can get annoying. Should it be hidden by default?

It shows up when compilation fails or when debugging anyways, which is when you want to use it. It will force you to use the hotkeys for compiling, running, debugging though.

**Comment by MadBit010** [comment]
I don't find it annoying when the terminal opens right away.
For the people who don't want that, you can give them the option to turn it off in the plugin settings.

**Comment by gosukiwi** [comment]
A setting would be nice :)
