### ISSUE TITLE
highlighting inc and dec

### ISSUE THREAD

**Issue by MadBit010** [gosukiwi/atom-agk#7]
[Inc ](https://www.appgamekit.com/documentation/language/32_inc.htm)and [Dec ](https://www.appgamekit.com/documentation/language/33_dec.htm)is not highlighted.

**Comment by MadBit010** [comment]
#import_plugin is also not highlighted.

**Comment by gosukiwi** [comment]
Thanks for the report!

Addressed in https://github.com/gosukiwi/atom-agk/commit/69ddb4b4bcacf859841282be2aa996eebdcfee7f and https://github.com/gosukiwi/atom-agk/commit/34114e42c552463ccd3820091e716a44b637ac82

Will publish it in version `0.3.3` later today.
