### ISSUE TITLE
Jump to declaration does not work

### ISSUE THREAD

**Issue by MadBit010** [gosukiwi/atom-agk#8]
When I right click on a function he offers me to go to the declaration. This does not work for me.
It would also be an advantage if it works for functions that are outside the project. That means they are inserted by #include and #insert.

**Comment by gosukiwi** [comment]
This only works for built-in functions, to open up the documentation page. It's not really a "Go To Definition" feature.

Maybe I should rename it to something more obvious, like "Open Documentation" or something.

I think "Go To Definition" (for functions) should be doable with the current implementation though. I'll open a new issue to investigate that further.

**Comment by MadBit010** [comment]
Maybe function help or command help? Or instead of help, you can call it description.

**Comment by gosukiwi** [comment]
This will be up in `v0.4.0` later today :)
